apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  # Enable script-based protocol mappers
  # Valid feature flags: https://www.keycloak.org/server/all-config#category-feature
  additionalOptions:
    - name: features
      value: "scripts"  # Can also use "scripts:v1" for explicit version

  # Existing configuration
  db:
    database: keycloak
    host: keycloak-db-rw.keycloak.svc
    passwordSecret:
      key: password
      name: keycloak-db-app
    port: 5432
    usernameSecret:
      key: username
      name: keycloak-db-app
    vendor: postgres
  hostname:
    strict: false
  http:
    httpEnabled: true
  instances: 1
  proxy:
    headers: xforwarded
